version: "3"
services:
  node-app:
    image: hamzaesmael/tresmerge-docker:tagname
    depends_on:
      - redis
    container_name: express-node-app-container
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
  #mongo-express:
    #depends_on:
     # - mongo
    #image: mongo-express
    #restart: always
    #ports:
      #- 8081:8081
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: example
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis:
    image: redis
  web:
    image: nginx:stable-alpine
    ports:  
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express-node-app-container
volumes:
  mongo-db:
  postgres-db: